### ISSUE TITLE
[FEATURE] support for Animated.ScrollView onScroll

### ISSUE THREAD

**Issue by usrbowe** [netceteragroup/skele#147]
If we want to use `Animated.ScrollView` and handle the `onScroll` event in native thread, there is currently no way to pass the `offsetY/X`, out of the onScroll prop.

In my example I used `react-native-reanimated`, so the entire event is driven in native thread. 
I can get offset values via `callback` and pass it back to `ViewportTracker` component via `ref`.

I created this PR, as a temporary workaround: #146

**Comment by ognen** [comment]
Hello,

I've examined #146 and closed it due to it not meeting the checks, and also having too many files changed.

I'm wondering if this feature is really necessary. Looking at the code example in block #146, don't you think that you should call the scroll views' scrollTo() method? that will trigger an onScroll event which in turn will update the tracker's state.

**Comment by usrbowe** [comment]
@ognen I admit the PR is not correct, I just used branch I forked. I might create a separate PR with cleaner code. But anyway I'm not even sure, if this is good approach for that. So it's more like open for discussion.

So the main problem is, when using `react-native-reanimated`, `skele` component should not assign onScroll event listener, but rather get value from outside. Right now if I combine `skele` and `react-native-reanimated` it will throw error as seen in this demo: https://snack.expo.io/@usrbowe2/skele-reanimated

If you remove the `<Viewport.Trcker />` all works fine.

**Comment by bevkoski** [comment]
Hi @usrbowe! I took a look at your Snack demo. It is true that there is an issue. Thanks for pointing it out.

However, setting the value from outside does not make much sense in the context of a "viewport tracker". Thus, I would for now consider the obstacle that you have experienced as a limitation of the tracker.

A potentially clean solution to your problem is to do a custom extension of [WithEvents](https://github.com/netceteragroup/skele/blob/5951cf6bf891b51889aba8e73540ca987b431e19/packages/components/src/shared/WithEvents.js) and call [`notifyViewportListeners`](https://github.com/netceteragroup/skele/blob/c8adda13a3e50ca81610565b42600cd5f93effcb/packages/components/src/viewport/tracker/index.js#L57) each time you want to communicate a viewport change to the `Viewport.Aware` components.

You can import `WithEvents` in your app like so:
```javascript
import { Mixins } from '@skele/components';
// use Mixins.WithEvents
```

**Comment by Hirbod** [comment]
@bevkoski could you maybe provide a little example? I have the same issue currently. I am using an react-native-reanimated ScrollView to make a Cube transition and I would like to know when load the next images. 

Currently I just get 

```
n is not a functin. (In nt(t)', 'n' is an instance of _)
```

```jsx
                <Viewport.Tracker>
                    <Animated.ScrollView
                        removeClippedSubviews={true}
                        ref={(scroller) => {this.scroller = scroller}}
                        style={StyleSheet.absoluteFillObject}
                        showsHorizontalScrollIndicator={false}
                        scrollEventThrottle={16}
                        pagingEnabled={true}
                        decelerationRate={'fast'}
                        contentContainerStyle={{width: width * stories.length}}
                        onScroll={event(
                            [
                                {
                                    nativeEvent: {
                                        contentOffset: { x },
                                    },
                                },
                            ],
                            { useNativeDriver: true },
                        )}
                        horizontal
                    />
                </Viewport.Tracker>
```

**Comment by bevkoski** [comment]
@usrbowe and @Hirbod, [here is a Snack](https://snack.expo.io/@bevkoski/viewport-aware-animated-scrollview) that shows how it can be done. Please check the `ViewportNotifier.js` file for the details.

**Comment by Hirbod** [comment]
Thank you very much! Looks great and easy to understand. Will give it a try tomorrow!

**Comment by Hirbod** [comment]
@bevkoski I've spent nearly 2 hours, but my Images won't change - they will be "stuck" on the placeholder.

It took my a while to figure out, that react-native-reanimated does not have "listener", but I found a way around and I log my methods, they get called (and btw, every single pixel of movement calls a setState, JS FPS drops to 4 after 20px auf swiping)

The way to use it with reanimated is like this btw:

```js
                    onScroll={event(
                        [
                            {
                                nativeEvent: {
                                    contentOffset: {
                                        x: x => block([
                                            set(this.state.x, x),
                                            call([x], this.setEventDataForNotifier)
                                        ])
                                    },
                                },
                            },
                        ],
                        {
                            useNativeDriver: true,
                        },
                    )}
```

and inside the function setEventDataForNotifier I set

```js
        this.setState({
            viewportOffsetX: x[0],
            shouldMeasureLayout: false
        })
```
But nothing happens. My cube gets transitioned but only with placeholders. 

P.S: my scrollview is horizontal, not vertical. I set the contentContainer to screenWidth * items

**Comment by Hirbod** [comment]
P.S. some side information: The images take 100% of width and height, so I display 1 image on the full screen and when I scroll horizontically, I snap to the next image... but from my point of view it should work, while it doesn't

**Comment by bevkoski** [comment]
@Hirbod, [the Snack](https://snack.expo.io/@bevkoski/viewport-aware-animated-scrollview) shows that it is possible to use Skele Components together with React Native's `Animated`. As it seems according to your findings, `react-native-reanimated` does not work exactly the same, so that might be one source of issues.

It is true that setting the state as it is done in the Snack is not optimal in terms of performance. The approach is used for clarity's sake. For optimal performance, `Mixins.WithEvents` should be extended in the class containing the `ScrollView` (in the case of the Snack, `App`). That way, unnecessary re-rendering will be avoided.

> The images take 100% of width and height, so I display 1 image on the full screen and when I scroll horizontically, I snap to the next image...

The 100% size images could affect the whole situation. You can check whether setting the [`preTriggerRatio` parameter](https://github.com/netceteragroup/skele/tree/master/packages/components#properties) to `0.5` helps.

I'm afraid I cannot offer you much more assistance beyond this. Thanks and good luck!

**Comment by Hirbod** [comment]
Thanks for your help though. I played around few more hours and got it work, but the performance is draining so badly, that my efforts to optimize everything, were much more worse. I ended up dropping skele and kinda switch over to FlatList

**Comment by mtourj** [comment]
If anyone is running into this issue like I was, here is my solution to this. It's a little hacky, but it solves the issues mentioned above with sluggishness and is the most flexible solution I could come up with!
`import { Mixins } from '@skele/components';
import React from 'react';
import { Animated, findNodeHandle } from 'react-native';

class ViewportTrackingAnimatedScrollView extends Mixins.WithEvents(
  {
    name: 'Viewport',
    inChildContext: true,
    notifiesWithLastEventOnAdd: true,
  },
  React.Component
) {
  viewportWidth = 0;
  viewportHeight = 0;

  render() {
    return (
      <Animated.ScrollView
        {...this.props}
        ref={(r) => {
          // We want to share this ref
          this._ref = r;
          this.props.innerRef?.(r);
        }}
        //@ts-ignore
        onScroll={Animated.forkEvent(this.props.onScroll, ({ nativeEvent }) => {
          if (this._ref)
            this.notifyViewportListeners({
              parentHandle: findNodeHandle(this._ref),
              viewportOffsetX: nativeEvent.contentOffset.x,
              viewportOffsetY: nativeEvent.contentOffset.y,
              viewportWidth: this.viewportWidth,
              viewportHeight: this.viewportHeight,
              shouldMeasureLayout: true,
            });
        })}
        onLayout={(event) => {
          this.viewportHeight = event.nativeEvent.layout.height;
          this.viewportWidth = event.nativeEvent.layout.width;
          this.props.onLayout?.(event);
        }}
      >
        {this.props.children}
      </Animated.ScrollView>
    );
  }
}

export default React.forwardRef((props, ref) => (
  // @ts-ignore
  <ViewportTrackingAnimatedScrollView {...props} innerRef={ref} />
));
`

Not exactly sure what shouldMeasureLayout does, so I have it constantly set to true to avoid extra re-renders, you can change this if you'd like, but I didn't notice any kind of performance hit so I kept it that way for my uses. :)
