### ISSUE TITLE
Are there any updated forks/alternatives to this library?

### ISSUE THREAD

**Issue by OmkarK45** [netceteragroup/skele#158]
Hi,
basically the title

It's been almost 5 years this library hasn't been updated,
any good alternatives/implementations?

**Comment by andon** [comment]
Hi @OmkarK45,

What you have written above is not an issue, but a question, hence I will close this issue.

While this library hasn't had any active development for a long time, that doesn't mean that it needs one. It has solved "the problem at hand", and there was no need to update anything since then. We still have projects (that are constantly being developed and updated) that are using this library and they are just fine.

**Comment by Durkaen** [comment]
Hi @andon,

First of all, I would like to thank you for your work, I use your service in many projects.

A few days ago, when I upgraded my project from react native version 0.74.5 to 0.75.2, I started getting the following warnings;

- Warning: WithListeners(Component) uses the legacy childContextTypes API which is no longer supported. Use React.createContext() instead.

- Warning: ViewportAware(View) uses the legacy contextTypes API which is no longer supported. Use React.createContext() with static contextType instead.

Will you have a work on this? Or do you have a suggestion that can help?
